webdriver.driver=chrome
webdriver.base.url=http://opencart.abstracta.us
serenity.project.name=EJERCICIO_1
thucydides.project.name=EJERCICIO_1
serenity.take.screenshots=AFTER_EACH_STEP
headless.mode=false